<?php
$css = [
    'estructura' => true,
    'tablas' => true,
    'filtros' => true
];
require_once APPROOT . '\views\includes/head.php';
?>
<div class="estructura">
    <?php require_once APPROOT . '\views\includes/navbar.php'; ?>
    <h1 class="titulo"><?php echo $data['titulo']; ?></h1>
    <?php require_once APPROOT . '\views\includes/filters.php'; ?>

    <div class="contenido">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga explicabo dolores corrupti ea quasi tenetur numquam sed dolore quia distinctio aliquid ut atque eveniet dolorum, amet ex. Ad, accusamus quidem.
        Sint similique, hic quibusdam inventore dicta accusamus assumenda velit distinctio reprehenderit, molestias vitae temporibus ea voluptates suscipit officia, error fuga laborum. Ullam ipsa optio illo itaque eligendi sint possimus assumenda!
        Molestiae, temporibus recusandae enim illum odit adipisci commodi asperiores maiores culpa aliquam tempore explicabo! Consectetur laudantium, alias, veniam laborum dolorum animi odio excepturi, dicta velit accusamus harum nostrum voluptas ex.
        Quae quo explicabo, officiis nobis, corrupti esse obcaecati sequi in amet aliquam error quisquam dolorem exercitationem similique quidem porro veritatis id sunt quasi eos omnis delectus tempora harum! Sed, recusandae!
        Excepturi placeat tenetur deserunt consequuntur, et officia, sit illum fuga repellat aliquam eligendi adipisci aliquid? Eos, autem dignissimos libero amet perferendis nihil inventore facere tempore hic ex harum dolorum itaque.
        Saepe voluptatibus eum commodi architecto, perferendis tempore obcaecati, veritatis reiciendis earum tenetur hic enim ipsum asperiores magnam? Iusto neque voluptates nulla praesentium quisquam? Totam excepturi architecto ipsam quis molestias quas.
        Deserunt cumque commodi quasi neque deleniti nemo ipsum aut voluptates adipisci necessitatibus optio eum illum ab ex saepe voluptate autem laborum molestias, reprehenderit quod harum enim quibusdam atque rem! Voluptas.
        At earum omnis quas excepturi ab commodi alias itaque quos ea architecto nobis consequuntur ex dolores quo cum sunt blanditiis ratione, amet asperiores? Corporis error atque mollitia? Nihil, corporis quas?
        Ipsum eos architecto ipsa laudantium minus et alias nihil voluptatum odio dolor nulla aut, fuga commodi asperiores, blanditiis soluta totam non ducimus doloremque animi praesentium. Deleniti repellat rem accusamus unde.
        Possimus, blanditiis sequi aspernatur nam quae nulla repellendus veritatis pariatur numquam corporis nostrum quia dolore quas nesciunt cum ea? Necessitatibus nesciunt veritatis tenetur dolorem dolorum modi optio totam excepturi quia.
        Cum aperiam sit praesentium veniam ab, dignissimos repellat recusandae officia amet corporis nulla corrupti tempora qui est. Quam, possimus numquam necessitatibus tempora, assumenda sequi omnis rem, esse laboriosam fugit illum?
        Soluta sint nisi asperiores magni. Similique asperiores accusantium amet, iure quisquam illo ea necessitatibus vero et aperiam facilis dolore delectus, numquam quos voluptatem explicabo veniam qui ab! Rerum, dolorum aspernatur?
        In molestias odio ipsam, facilis possimus itaque, eius assumenda tenetur, doloremque dolor aperiam dolore id ea voluptate blanditiis ratione ipsa neque quod impedit et consectetur? Voluptatum voluptas eligendi non assumenda!
        Ab soluta ducimus fugit sed? Quae blanditiis, excepturi repudiandae reprehenderit soluta corrupti at laboriosam doloremque ipsa earum commodi quas incidunt placeat quaerat deleniti est optio culpa atque vel rem sequi.
        Amet nisi quibusdam deserunt porro debitis illo cum perferendis! Esse eius ea qui earum tempora deserunt quod repudiandae maiores totam ducimus facilis aliquid necessitatibus, quasi voluptatem iusto perspiciatis dolorem reiciendis.
        Illum quis, commodi ducimus, obcaecati suscipit cupiditate ea magni totam non corporis harum deserunt ipsam rem dolores! Impedit odio, maxime qui architecto velit ratione suscipit, repellat, sit at explicabo officiis!
        Exercitationem inventore, ut veritatis iusto enim provident sit laudantium qui quasi aperiam quis impedit ipsum. Tenetur ad magni voluptas, incidunt numquam sint sed cum accusamus animi illo? Ab, repellat non!
        Laboriosam aperiam aspernatur sunt distinctio reprehenderit tenetur fuga, maiores consectetur, debitis quibusdam vel excepturi officia pariatur necessitatibus soluta nemo, aliquam ipsum. Esse commodi id aperiam. Ab perferendis quod architecto ut.
        Culpa veniam facilis provident repellat ab ea laborum aut minus, ut iusto, et consectetur dignissimos quis. Culpa, atque? Obcaecati dicta, soluta commodi numquam eaque iusto odit laborum. Corporis, dolore architecto?
        Sed asperiores exercitationem alias autem ut tempore fugiat voluptatum. Nemo dolores deserunt et voluptates voluptatum molestiae corrupti quo accusantium. Tenetur minima id recusandae cumque voluptas velit in et, quas eius?
        Ex similique laboriosam optio, consequatur libero odit soluta eaque enim iusto nobis explicabo tempora placeat beatae fugit dolor totam! Qui, tempore placeat maxime quaerat magnam vel quia a ipsam quisquam?
        Totam quos quisquam, repellendus esse sunt dolore provident tempora dolorem maiores ex soluta reprehenderit error assumenda unde rerum quasi magni dignissimos, quis consectetur facilis. Nemo accusantium ducimus soluta non error.
        Fugit inventore laborum porro? Corporis quis dolorem repellat ipsam quibusdam explicabo dolore, quos temporibus qui nulla reprehenderit consequatur, fugit consequuntur reiciendis! Nostrum quia enim consectetur officiis. Voluptatem alias distinctio nobis?
        Natus, quia? Odit voluptatibus cupiditate ipsa. Temporibus incidunt, possimus voluptatibus tempora eligendi, eius dolore, voluptatum unde dicta error similique voluptate repudiandae minus totam quas assumenda accusamus a corrupti? Facilis, repellendus?
        Nesciunt consequuntur necessitatibus provident, eveniet nostrum molestiae in! Nostrum rerum sed doloremque praesentium tempora quas velit, eveniet fuga minus laborum eius nesciunt ipsum officia soluta dolor odit illo. Corporis, iusto?
        Nisi, quod nulla. Incidunt a laborum provident hic est dicta corporis. Quasi ullam est a eius quia amet consequatur? Odio deleniti accusantium, ratione esse alias pariatur dolorum dolor nostrum molestias?
        Minima ut ratione delectus, quibusdam consectetur obcaecati aut repudiandae numquam reiciendis, consequatur, ducimus recusandae. Voluptate nesciunt consequatur minus magnam iste, facere atque possimus sint quisquam optio architecto neque labore cupiditate!
        A omnis iste doloremque quasi quis reprehenderit modi, ipsam accusantium ducimus et similique quaerat cupiditate porro dicta tempora beatae deleniti nesciunt alias voluptate optio? Doloremque eveniet nobis magni tempora laudantium?
        Ipsa quae nisi natus odio voluptatum sapiente rerum doloribus dolor at repellat necessitatibus reiciendis, aliquid perferendis, adipisci ullam eos sunt doloremque incidunt, nesciunt consequatur. Dignissimos ipsa dicta voluptatem cumque ratione!
        Quis, repellat. Odit aperiam beatae temporibus id aspernatur officia neque molestias repellat adipisci molestiae. Odit perferendis hic obcaecati similique dolor quibusdam totam excepturi rerum ducimus. Consequatur error quis sunt sequi!
        Ipsum cum odit distinctio esse quo tenetur ducimus adipisci iure quae, veritatis est, porro commodi pariatur voluptatum. Illum dolore delectus minus, praesentium doloremque recusandae nam aut culpa, quos inventore officiis!
        Facere id, suscipit aspernatur rerum voluptate amet nam alias, pariatur qui asperiores aperiam corrupti iure a dolorum in culpa vel. Perferendis, error? Enim, totam in reprehenderit consequatur assumenda ab quae!
        Eius at alias tempore quos placeat et rem sit velit animi, facere maxime facilis est vitae cupiditate nisi recusandae dolor labore, repellendus aliquam error magni! Corporis non eveniet cum delectus.
        Autem, in commodi. Cupiditate voluptas aut alias sed nihil nam nisi animi dolorem doloribus sint laborum nostrum, error ullam mollitia asperiores rerum ad saepe facere ea? Molestiae exercitationem minus enim?
        Cum, minima corporis! Facilis ducimus eos accusamus nesciunt illum. Eaque beatae totam rem assumenda. Voluptatibus delectus aliquid, amet facere nisi explicabo impedit quae molestias. A voluptate suscipit id impedit minus?
        Eveniet, provident. Facilis at, vel veniam consectetur debitis obcaecati blanditiis officia expedita quasi explicabo magnam consequuntur eaque quis provident, odit iste fugiat quaerat dolores numquam culpa. Neque sunt iure illum?
        Voluptatem provident numquam obcaecati totam possimus! Voluptatibus, quibusdam. Consequuntur iusto deserunt asperiores aperiam qui. Eveniet sit, cumque porro dolorum iusto neque ratione doloremque, iste deleniti atque aperiam asperiores at itaque!
        Quidem quam harum atque natus, minima tempora quibusdam aspernatur labore. Repellendus sit, facere quidem, hic maxime ut, quibusdam dolor nostrum fugit corporis autem laborum quae deserunt repellat a quod nisi.
        Itaque quam fuga delectus et exercitationem molestiae nihil eum, accusantium quisquam, quis ex laborum! Beatae vero non nostrum vel quo dolor quos rerum, dolorum nobis ab minus, laborum asperiores molestiae?
        Quaerat, numquam perferendis repudiandae, ipsa obcaecati eaque consequuntur in iusto, explicabo quibusdam omnis amet tenetur nisi deserunt. Maxime pariatur sunt tempore est quia numquam, laborum aliquid fuga distinctio vero ipsam.
        Illum consectetur a mollitia adipisci porro. Dignissimos consequatur possimus nisi alias iusto ratione laborum modi adipisci voluptas, commodi, ex reprehenderit debitis temporibus quas. Aperiam explicabo perspiciatis voluptatem mollitia quae officiis.
        Eaque id quam debitis, atque odit, sed veritatis delectus qui obcaecati porro, necessitatibus voluptas saepe. Quo quos consequuntur atque sit illo. Laborum, enim ea pariatur totam voluptas magni veniam possimus?
        Tenetur consequatur culpa facilis tempora quam animi nulla quas voluptates ullam fugiat dolore, assumenda quaerat ipsa magnam est pariatur quasi atque velit, rerum omnis. Eveniet quasi ipsa nesciunt impedit mollitia.
        Dolores eaque porro deleniti qui soluta inventore pariatur similique ullam culpa veniam voluptatibus est enim, magni eligendi, tempora architecto quasi quam laudantium blanditiis excepturi ut neque provident animi sapiente. Nisi?
        Dolorum expedita dignissimos praesentium veniam ipsam quia deleniti. Sint, maxime autem. Dignissimos quas quos nostrum, pariatur quibusdam quaerat architecto, nulla illo error non soluta, sit porro modi autem aliquam. Distinctio!
        Nobis qui nulla laudantium saepe sint laboriosam magni sit, iste enim ut sunt veritatis vitae minima eos expedita beatae quas id repellat, quidem explicabo cumque minus delectus officia! Neque, aliquam?
        Illo eligendi, quod ducimus ad asperiores aliquid sapiente aut tenetur incidunt, a voluptas nisi ratione? Quaerat repellendus velit nesciunt laborum perspiciatis recusandae officiis nisi quos facere accusamus. Laudantium, sunt corrupti!
        Libero itaque suscipit, minus totam ea expedita facilis quas debitis incidunt at dicta, ad laborum quam quod sit odio repellat iusto vero accusantium temporibus magnam enim fugit nulla. Libero, cumque.
        Necessitatibus fugiat commodi voluptatum? Consectetur repudiandae eligendi voluptatem blanditiis quidem praesentium labore modi nam, distinctio ea beatae consequuntur fugit dolorum facilis? Cumque incidunt harum ratione quae aspernatur nostrum doloremque consequatur?
        Quae, esse odio ipsa nesciunt accusamus minima consequatur sapiente odit alias quaerat possimus tenetur tempora magnam ducimus, porro molestiae. Molestias, explicabo. Enim officia voluptatibus deserunt quae totam sapiente architecto saepe.
        Velit nam necessitatibus maxime explicabo veritatis iure! Rerum voluptatem quia temporibus ex excepturi aliquam veniam placeat nulla. Nesciunt amet id magnam molestias totam at iste dolor veniam, velit voluptatem perferendis.
        Autem iure ducimus officia deserunt cum commodi minima quia ullam et sunt deleniti voluptatum omnis error cumque, debitis sequi, dignissimos totam assumenda culpa excepturi. Nihil eos omnis voluptatem velit asperiores?
        Blanditiis cumque alias culpa vero ad. Eaque distinctio laudantium fuga esse aliquam sequi labore saepe eos vitae natus debitis, minima aspernatur nesciunt unde sapiente sunt. Quam consequuntur perspiciatis harum eum!
        Tempora ipsum ad magni expedita sit aliquid consequuntur alias, vel quia dolores cupiditate quam odit animi laborum in earum minima exercitationem rerum aliquam? Tempora modi amet eius, sit eos deleniti?
        Suscipit sapiente laborum eaque? Omnis, voluptate illo. Suscipit aut similique voluptatem voluptas eligendi deserunt odit ab cum commodi ullam omnis doloribus ducimus sed quas, a provident nostrum. Quidem, minus facere?
        Ipsa eius nemo similique commodi sed eaque maxime quam cumque itaque non. Illo incidunt distinctio, qui delectus perferendis labore totam! Porro deserunt aliquam libero a ducimus laboriosam doloribus, eius molestiae.
        Rem dignissimos nesciunt expedita, aspernatur placeat illo delectus, omnis dicta, mollitia perspiciatis modi. Asperiores, corrupti ipsam quos eos beatae iure ea voluptate eaque voluptas non cumque iusto culpa ratione similique!
        Fugit cum minima necessitatibus dolor voluptate dolorum cumque quam dignissimos, ad culpa error corrupti eveniet recusandae illum cupiditate magni nihil reiciendis odio magnam optio ducimus nesciunt, tempore aliquam debitis? Reprehenderit!
        Sit cupiditate voluptatum odio quidem, illum ducimus necessitatibus rerum iure incidunt voluptates error minima neque repellendus laudantium expedita tempora. Similique nihil, eum esse accusamus quos eaque reprehenderit repudiandae beatae libero?
        Sint minima omnis iste sapiente odio facere vel fuga fugiat aspernatur nesciunt nobis voluptates maiores, dolorem ullam tenetur commodi beatae itaque! Blanditiis possimus ex, autem iure expedita ullam consectetur tempora.
        Molestiae provident pariatur eveniet ad cupiditate tempora asperiores facilis, sed numquam, ipsa fugiat minima, doloribus laudantium qui alias nulla sunt repellat obcaecati reprehenderit consequuntur veniam rem. Totam quod molestiae sit.
        Reprehenderit amet sequi, asperiores modi, esse libero nulla, blanditiis maxime ipsum assumenda itaque dolores nihil ut veniam nesciunt sint similique corporis eum error repellendus minima dignissimos cum? Ea, voluptatibus voluptate.
        Aperiam ad sapiente labore magni qui harum nostrum optio asperiores unde dolorem quae libero totam doloribus, dolor suscipit? Perspiciatis tempore ipsum qui debitis tempora ut quo aspernatur optio aut at?
        Molestiae dolor eius magni aliquid iure accusamus perferendis doloremque quisquam sit vel, enim commodi odit recusandae quis blanditiis numquam nisi fugiat ratione repellendus eum in rem, ipsam aut. Vero, facere!
        Provident aperiam quis cumque facilis at optio, iusto suscipit necessitatibus delectus aut, harum, dignissimos corporis aliquam veniam ipsam. Debitis assumenda illo aspernatur et, minus nam quis! Placeat modi cumque necessitatibus.
        Temporibus ut maxime sit aperiam, vitae magnam, explicabo id excepturi commodi cum, placeat dicta eius similique. Eum sequi iste, totam explicabo voluptatum modi praesentium neque ex laudantium illum sapiente. Sit?
        Distinctio ipsam, odio rerum mollitia accusantium minus aperiam delectus necessitatibus quo quisquam. Quidem ut aperiam aliquid natus corrupti eum doloremque ducimus, doloribus impedit! Labore tempora commodi molestiae dolor optio ipsum.
        Non perferendis iste, enim, necessitatibus at officia velit ullam nemo similique nisi dignissimos dolorem aperiam ab amet eaque eligendi delectus! Earum necessitatibus laborum alias tempora totam, in qui porro distinctio.
        Accusamus explicabo ut impedit dicta, voluptatum eum doloribus doloremque voluptate at voluptatibus nihil, voluptates nemo, quasi tempore modi illo numquam ducimus recusandae quas? Amet rem dicta corporis sint nihil harum.
        Reprehenderit at harum ullam quidem reiciendis. Deserunt voluptatem officiis sunt itaque ab fugiat explicabo, numquam unde, sit iste fuga perspiciatis culpa molestiae qui consequuntur tempora labore dignissimos hic minima molestias.
        Quisquam reiciendis ducimus suscipit, commodi cum fugit, dicta exercitationem porro repudiandae fugiat doloribus enim possimus quo voluptatibus consequatur adipisci expedita optio odit eaque nisi esse sequi itaque dignissimos. Id, vel!
        Expedita quidem illum commodi in consequuntur? Delectus nostrum nihil cumque repudiandae natus, eaque quo voluptatibus aliquam iusto facilis reiciendis ex corporis perferendis beatae accusamus voluptatem amet sunt, quaerat dolor ducimus!
        Ut dolor, temporibus magnam nihil repudiandae natus architecto expedita voluptate aliquid omnis ratione voluptatem repellendus commodi! Labore totam, dolores iste nihil veritatis nulla ex debitis odio blanditiis. Quasi, harum iste.
        Iusto perferendis dolore odio nam quae. Atque ea tempore accusamus aspernatur praesentium voluptatem at eligendi? Fugiat illo porro quod hic. Possimus maiores nesciunt temporibus dolor odio ex distinctio dolorum deleniti!
        Quis, sequi! Corporis minus accusantium dolores, voluptatum fuga ipsa illo reprehenderit accusamus! Laudantium labore a maiores voluptatibus ipsa quos voluptates reiciendis! Possimus animi maiores et excepturi deserunt consequatur magnam architecto.
        Eligendi enim cum officiis officia deserunt voluptatum, ipsam illo doloremque in ex, veniam similique voluptatibus ipsa debitis quisquam. Error, nam dolore! Natus, recusandae ab nam consequatur facere accusamus iure itaque?
        Atque modi quos quaerat doloremque quae repudiandae! Dolor mollitia tempore optio facilis aspernatur dolores, ab dolore accusantium, officia similique commodi repellendus minus facere! Omnis similique tenetur magni recusandae natus assumenda.
        Adipisci culpa provident ea reprehenderit harum ipsum, praesentium, delectus eius nostrum et similique amet atque quidem excepturi aperiam, totam quasi saepe. Pariatur id neque corporis laborum minus quisquam, laudantium alias?
        Eligendi vel doloribus magni optio veritatis veniam non in nemo expedita, exercitationem a fugit cupiditate inventore mollitia necessitatibus id consequuntur excepturi quia voluptatibus adipisci ex delectus? Natus deleniti ea doloribus!
        Iusto, tempore non tempora autem consequuntur suscipit voluptatem dolore natus modi at? Saepe totam minus iure iste rerum unde atque. Esse adipisci alias quam expedita labore, provident architecto perferendis corrupti!
        Placeat itaque quia deleniti aliquid ullam ipsum, eius aliquam voluptas aspernatur soluta impedit doloribus quas nulla recusandae natus cum commodi consequuntur expedita nihil veniam magnam. Accusantium sit reiciendis quaerat debitis.
        Quasi alias eum eligendi ut ducimus animi culpa! Maiores corporis veniam facere quam dolores ipsum ducimus voluptatibus laudantium minus minima dolore sit alias beatae, pariatur repudiandae voluptatum! Quibusdam, ipsum dignissimos.
        Laboriosam minima eligendi debitis vero quidem, enim modi voluptas necessitatibus odit, ullam tempora molestias! Provident, minima earum aperiam ipsam eos animi vitae fuga a modi voluptate cum, pariatur, et laborum!
        Reiciendis eveniet, tempora nulla praesentium voluptatem expedita illo rerum culpa sint nemo vero molestiae numquam iste corporis nobis accusantium non officia quasi recusandae. Quidem nam distinctio magni sit repellendus nemo.
        Necessitatibus dolor fugiat magni est labore, cum omnis fugit aut. Delectus quaerat optio architecto, cumque voluptates nesciunt minus, in cupiditate, quas accusantium eos suscipit consequuntur vitae voluptatibus quidem blanditiis commodi.
        Corporis, temporibus architecto dolores magni aperiam ipsum nam totam sit illo quam. Itaque, ipsa perspiciatis eius delectus aliquam voluptates impedit quae dolor fugit temporibus magnam sed deleniti eos non odit.
        Tempore delectus quaerat libero ullam explicabo esse aperiam saepe nesciunt fugiat architecto ut, repudiandae non incidunt dolor provident porro. Iusto recusandae ipsam aliquid reiciendis a quas esse eum temporibus similique!
        Ipsam, natus inventore fugit maxime earum error veniam a alias tempora qui deleniti rem ad. Est obcaecati laborum porro quo, nemo eum voluptatum libero labore nam, corrupti esse dignissimos asperiores!
        Pariatur est sunt repudiandae modi, veniam qui, dicta necessitatibus reprehenderit provident consequatur, doloribus odio dolores quas placeat. Recusandae veritatis quae vel rerum fugit inventore pariatur at voluptatum. Doloremque, animi autem.
        Aliquid commodi dolores quam voluptate dignissimos neque, vel quos fuga exercitationem nemo provident dolor expedita libero in maxime sed sapiente eos ducimus officia nulla, atque sunt nihil, nostrum velit? Quo?
        Saepe repellendus eligendi praesentium repellat veniam distinctio impedit, fugiat fugit explicabo aliquid porro veritatis quia nisi id deleniti suscipit similique obcaecati nemo recusandae vero? Nihil expedita quidem dicta cupiditate ipsam.
        Iste, eius officiis at magni placeat voluptas illo adipisci ex consectetur reiciendis expedita in ea, qui, magnam porro facilis nostrum repudiandae saepe. Corporis, reprehenderit ad fugiat expedita mollitia eius porro.
        Ab nam, voluptates, aliquam, quidem quas iste totam dolorum officiis tempore sunt ullam tenetur quasi omnis exercitationem architecto eum minus non doloribus nemo possimus! Laudantium aliquam omnis dolor ipsum possimus!
        Reiciendis, temporibus consequuntur ducimus quis, provident officiis omnis, aliquam amet saepe eligendi consequatur repellendus perspiciatis quos. Mollitia quis, iure adipisci, fuga in, debitis ullam facere tenetur natus veniam molestiae voluptas?
        Voluptate iste sit, cumque, optio aliquid beatae voluptatum reiciendis, ipsum debitis adipisci magnam ullam dignissimos minus nulla quos! Eos corporis magnam perferendis quas explicabo reiciendis ut odit magni adipisci expedita.
        Rem odio velit quibusdam pariatur cum dignissimos repellendus optio obcaecati numquam enim, minus aliquid aut reprehenderit accusantium nesciunt porro expedita aliquam. Quo rem veritatis dicta incidunt temporibus nam porro et.
        Voluptate fugit soluta vero omnis est dolorem doloribus repudiandae aliquid, voluptas unde nisi libero quos et possimus illo sequi praesentium a. Impedit atque, dolor odit molestias et beatae quae mollitia?
        Libero eos tenetur asperiores quas similique, optio saepe debitis rerum perferendis quam eum odio! Ullam, voluptatem. Quisquam, voluptatibus quo expedita neque ex earum impedit quidem, vitae animi ipsa provident natus!
        Laboriosam facere, voluptates voluptate modi repellat eius, cumque magnam deleniti molestiae odio, consequuntur aliquid quaerat doloribus pariatur odit optio in ipsa a rerum at! Minus aspernatur facere ad fugit harum.
        Inventore doloremque necessitatibus, laudantium aperiam, rerum eveniet deserunt beatae autem ratione eos ipsum? Quos recusandae itaque cupiditate officia earum veritatis quaerat aut, aspernatur at laborum repellendus repudiandae repellat quia minus.
    </div>
</div>
<?php
require_once APPROOT . '\views\includes/footer.php';
?>